title:  <p align="center"> Rashmi Salankar </p>
logo: /assets/img/logo.png
description:
<p align="center">
<br>   
  I'm a fellow student at Upgrad
  <br>
</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
